### ISSUE TITLE
Is this licensed for use?

### ISSUE THREAD

**Issue by apotheon** [yb66/RandomPerson#2]
I see no license in this project.  Is it just well-hidden?  Did you forget to include a license?  Do you just want to make it illegal for others to use this?  Your licensing intentions are not clear.

**Comment by apotheon** [comment]
Ignore that.  I somehow missed the license at the bottom of the README.  I'll submit a pull request for a LICENSE file and gemspec update.

**Comment by yb66** [comment]
Hi @apotheon 

Thanks. Just make sure to use licence (noun) and license (verb) and I'll accept it :-)

Regards,
yb66

**Comment by apotheon** [comment]
I've updated the name of the LICENCE file.  Nothing else in the actual commit contains "license", unless it's legal text (which I don't typically mess with when copying a specific legal document) or a configuration property (which I'd expect to break the gem).  Do you want me to delete the branch and start over so the commit log contains only Britishisms?
